### PR TITLE
fix: Make ModalStandardBottomSheet collapsed by default

### PR DESCRIPTION
**Pull request by MartinZikmund**
﻿GitHub Issue: fixes https://github.com/unoplatform/Uno.Gallery/issues/137

## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description

Modal sheet was initially visible when the window was resized.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Tested UWP
- [ ] Tested iOS
- [ ] Tested Android
- [x] Tested WASM
- [ ] Tested MacOS
- [x] Contains **No** breaking changes

### CODE REVIEW

**Review by ajpinedam — APPROVED** [review]

**Review by carldebilly — APPROVED** [review]

**Comment by MartinZikmund** [comment]
@carldebilly Seems I don't have permission to merge here, can you merge the changes please?

**Pull request closed without merging**
